### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by thefranke** [jglrxavpok/jglrxavpok.github.io#3]
Hey just stumbled across your blog. Can you add RSS feeds to it? Jekyll has support for that and would enable everyone to subscribe to your posts!

Cheers

**Comment by jglrxavpok** [comment]
There is already a RSS feed for my blog ( https://jglrxavpok.github.io/feed.xml ) but it is true that I don't really show it on the blog.
This is something I will need to add!

**Comment by thefranke** [comment]
Awesome, thanks!
